# -------------------------------------------------------
# CIB Seven REST API base URL
# -------------------------------------------------------
quarkus.rest-client.cib-seven.url=http://localhost:7093
cib-seven.auth.username=demo
cib-seven.auth.password=demo

# -------------------------------------------------------
# Quarkus
# -------------------------------------------------------
quarkus.package.type=fast-jar
quarkus.banner.enabled=true
quarkus.banner.path=banner.txt
quarkus.swagger-ui.always-include=true
quarkus.kogito.devservices.enabled=false
quarkus.log.level=INFO
quarkus.log.category."de.cib".level=DEBUG
